[package]
name = "wyrmroot-bootstrap"
version = "0.0.0"
edition = "2024"
publish = false
description = "Primordial Wyrmroot bootstrap application"
license = "GPL-3.0-or-later"

[lib]
path = "src/lib.rs"

[[bin]]
name = "wyrmroot-bootstrap"
path = "src/main.rs"
test = false
bench = false
required-features = ["native-bootstrap"]

[features]
default = []
native-bootstrap = []
loader-smoke-integration = ["dep:wyrmroot-loader"]
native-loader-smoke-integration = ["native-bootstrap", "loader-smoke-integration"]
primordial-test-support = ["wyrmroot-runtime/primordial-test-support"]
primordial-blocking-cleanup = ["native-bootstrap", "primordial-test-support"]
primordial-user-exception = ["native-bootstrap", "primordial-test-support"]
primordial-invalid-return = ["native-bootstrap", "primordial-test-support"]

[dependencies]
deepwyrm-syscall.workspace = true
wyrmroot-bootfs = { path = "../crates/wyrmroot-bootfs" }
wyrmroot-bootstrap-proto = { path = "../crates/wyrmroot-bootstrap-proto" }
wyrmroot-loader = { path = "../crates/wyrmroot-loader", optional = true }
wyrmroot-runtime = { path = "../crates/wyrmroot-runtime" }

[dev-dependencies]
wyrmroot-bootfs = { path = "../crates/wyrmroot-bootfs", features = ["builder"] }

[lints.rust]
unsafe_code = "deny"
unused_crate_dependencies = "deny"
