[workspace]
resolver = "3"
members = [
    "bootstrap",
    "crates/wyrmroot-bootfs",
    "crates/wyrmroot-bootstrap-proto",
    "crates/wyrmroot-loader",
    "crates/wyrmroot-runtime",
    "loader",
    "tools/xtask",
    "userspace/hello",
    "userspace/i-capability",
    "userspace/i2-stress",
    "userspace/init0",
    "userspace/loader-smoke",
]

[workspace.package]
version = "0.0.0"
edition = "2024"
license = "GPL-2.0-or-later"
repository = "https://github.com/JTM-rootstorm/wyrmroot"

[workspace.dependencies]
deepwyrm-abi = { git = "https://github.com/JTM-rootstorm/deepwyrm.git", rev = "cfc69bd8a49819ce1cda1a132cf56e55c93f92e4" }
deepwyrm-syscall = { git = "https://github.com/JTM-rootstorm/deepwyrm.git", rev = "cfc69bd8a49819ce1cda1a132cf56e55c93f92e4" }
uefi = { version = "=0.39.0", default-features = false, features = ["alloc", "global_allocator", "panic_handler"] }
