[workspace]
resolver = "3"
members = [
    "bootstrap",
    "crates/wyrmroot-bootfs",
    "crates/wyrmroot-bootstrap-proto",
    "crates/wyrmroot-loader",
    "crates/wyrmroot-runtime",
    "loader",
    "tools/xtask",
    "userspace/hello",
    "userspace/init0",
]

[workspace.package]
version = "0.0.0"
edition = "2024"
license = "GPL-3.0-only"
repository = "https://github.com/JTM-rootstorm/wyrmroot"

[workspace.dependencies]
deepwyrm-abi = { git = "https://github.com/JTM-rootstorm/deepwyrm.git", rev = "79c2e365901ab95d04e5f6877b87b109f61f7ca4" }
uefi = { version = "=0.39.0", default-features = false, features = ["alloc", "global_allocator", "panic_handler"] }
