[package]
name = "wyrmroot-init0"
version = "0.0.0"
edition = "2024"
publish = false
description = "Temporary native WYR0 init0 process"
license = "GPL-3.0-or-later"

[lib]
path = "src/lib.rs"

[[bin]]
name = "wyrmroot-init0"
path = "src/main.rs"
test = false
bench = false
required-features = ["native-init0"]

[features]
default = []
native-init0 = []

[dependencies]
deepwyrm-syscall.workspace = true
wyrmroot-bootfs = { path = "../../crates/wyrmroot-bootfs" }
wyrmroot-loader = { path = "../../crates/wyrmroot-loader" }
wyrmroot-runtime = { path = "../../crates/wyrmroot-runtime" }

[dev-dependencies]
wyrmroot-bootfs = { path = "../../crates/wyrmroot-bootfs", features = ["builder"] }

[lints.rust]
unsafe_code = "deny"
unused_crate_dependencies = "deny"
