[package]
name = "wyrmroot-bootfs"
version = "0.0.0"
edition = "2024"
license = "GPL-2.0-or-later"
publish = false
description = "Wyrmroot bootstrap archive support"

[lib]
path = "src/lib.rs"

[features]
default = []
builder = []

[[bin]]
name = "wyrmroot-bootfs-build"
path = "src/bin/build.rs"
required-features = ["builder"]
test = false
bench = false
