[package]
name = "wyrmroot-runtime"
version = "0.0.0"
edition = "2024"
license = "GPL-2.0-or-later"
publish = false
description = "Minimal native runtime support for Wyrmroot"

[lib]
path = "src/lib.rs"

[features]
default = []
primordial-test-support = []
wyr1-test-evidence = []

[dependencies]
deepwyrm-syscall.workspace = true
wyrmroot-loader = { path = "../wyrmroot-loader" }

[lints.rust]
unsafe_code = "deny"
unused_crate_dependencies = "deny"
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("wyrmroot"))'] }
