[package]
name = "xtask"
version.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later"
repository.workspace = true
publish = false

[dependencies]
deepwyrm-abi.workspace = true
wyrmroot-bootfs = { path = "../../crates/wyrmroot-bootfs", features = ["builder"] }

[dev-dependencies]
wyrmroot-i-capability = { path = "../../userspace/i-capability" }
